# Generated by Django 5.2.8 on 2025-11-21 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_branch_created_at_branch_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Fecha del registro de asistencia.')),
                ('status', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('PT', 'Presente tarde'), ('F', 'Franco'), ('FC', 'Franco compensatorio'), ('FE', 'Feriado trabajado'), ('V', 'Vacaciones'), ('AFDS', 'Acuerdo fin de semana'), ('OTRO', 'Otro')], help_text='Código de asistencia.', max_length=5)),
                ('notes', models.TextField(blank=True, help_text='Comentarios u observaciones.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('employee', models.ForeignKey(help_text='Empleado al que corresponde el registro.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-date', 'employee__last_name', 'employee__first_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'branch', 'employee', 'date'), name='unique_attendance_per_employee_date')],
            },
        ),
    ]
