# Generated by Django 5.2.8 on 2025-11-21 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_branch_created_at_branch_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROCESS', 'En proceso'), ('SENT', 'Enviado'), ('DELIVERED', 'Entregado / Recibido'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Estado actual del pedido.', max_length=20)),
                ('category', models.CharField(help_text='Categoría general del pedido (Librería, Limpieza, etc.).', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta')], default='NORMAL', help_text='Prioridad del pedido.', max_length=10)),
                ('comments', models.TextField(blank=True, help_text='Comentarios generales de la sucursal sobre el pedido.')),
                ('purchasing_notes', models.TextField(blank=True, help_text='Notas internas del área de compras.')),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en que se creó el pedido.')),
                ('in_process_date', models.DateTimeField(blank=True, help_text="Fecha en que Compras tomó el pedido como 'En proceso'.", null=True)),
                ('sent_date', models.DateTimeField(blank=True, help_text="Fecha en que el pedido fue marcado como 'Enviado'.", null=True)),
                ('delivered_date', models.DateTimeField(blank=True, help_text="Fecha en que la sucursal marcó el pedido como 'Entregado / Recibido'.", null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, help_text='Fecha en que el pedido fue cancelado.', null=True)),
                ('branch', models.ForeignKey(help_text='Sucursal que realiza el pedido.', on_delete=django.db.models.deletion.PROTECT, related_name='internal_orders', to='companies.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Usuario que canceló el pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_orders_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el pedido.', on_delete=django.db.models.deletion.PROTECT, related_name='internal_orders_created', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, help_text="Usuario que marcó el pedido como 'Entregado / Recibido'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_orders_delivered', to=settings.AUTH_USER_MODEL)),
                ('in_process_by', models.ForeignKey(blank=True, help_text="Usuario que marcó el pedido como 'En proceso'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_orders_in_process', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, help_text="Usuario que marcó el pedido como 'Enviado'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_orders_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido interno',
                'verbose_name_plural': 'Pedidos internos',
                'ordering': ['-requested_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del producto/insumo solicitado.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad solicitada.', max_digits=10)),
                ('unit', models.CharField(default='unid', help_text='Unidad de medida (unid, caja, pack, litro, etc.).', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas específicas del ítem (marca sugerida, etc.).')),
                ('order', models.ForeignKey(help_text='Pedido al que pertenece este ítem.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.internalorder')),
            ],
            options={
                'verbose_name': 'Ítem de pedido interno',
                'verbose_name_plural': 'Ítems de pedido interno',
            },
        ),
    ]
