# Generated by Django 5.2.8 on 2025-12-28 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_branch_created_at_branch_updated_at_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido interno', 'verbose_name_plural': 'Pedidos internos'},
        ),
        migrations.AddField(
            model_name='internalorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se marcó como eliminado.', null=True),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que marcó el pedido como eliminado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_orders_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el pedido fue eliminado lógicamente.'),
        ),
        migrations.AddIndex(
            model_name='internalorder',
            index=models.Index(fields=['company', 'branch', 'status'], name='orders_inte_company_558a20_idx'),
        ),
        migrations.AddIndex(
            model_name='internalorder',
            index=models.Index(fields=['is_deleted'], name='orders_inte_is_dele_6446aa_idx'),
        ),
    ]
