# Generated by Django 5.2.8 on 2025-11-17 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_branch_created_at_branch_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Fecha del cierre de caja.')),
                ('total_sales', models.DecimalField(decimal_places=2, help_text='Total de ventas del día (según sistema).', max_digits=12)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto en efectivo declarado.', max_digits=12)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto total por tarjetas.', max_digits=12)),
                ('qr_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto total por cobros con QR / billetera virtual.', max_digits=12)),
                ('other_payments_amount', models.DecimalField(decimal_places=2, default=0, help_text='Otros medios de pago (cheques, transferencias, etc.).', max_digits=12)),
                ('extra_incomes', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos extra (no ventas, ej. devoluciones de gastos).', max_digits=12)),
                ('extra_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Egresos extra (pagos varios desde la caja).', max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia de caja declarada (sobrante o faltante).', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observaciones del encargado sobre el cierre.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='companies.branch')),
                ('closed_by', models.ForeignKey(blank=True, help_text='Usuario que confirmó el cierre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'verbose_name': 'Cierre de caja diario',
                'verbose_name_plural': 'Cierres de caja diarios',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'branch', 'date'), name='unique_daily_cash_per_branch_and_date')],
            },
        ),
    ]
