# Generated by Django 5.2.8 on 2025-11-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen adjunta del cierre de caja.', upload_to='dailycash_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('daily_cash', models.ForeignKey(help_text='Cierre de caja al que pertenece la foto.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cash.dailycash')),
            ],
            options={
                'verbose_name': 'Foto de cierre de caja',
                'verbose_name_plural': 'Fotos de cierre de caja',
            },
        ),
    ]
