# Generated by Django 5.2.8 on 2025-11-21 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_dailycashphoto'),
        ('companies', '0002_branch_created_at_branch_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailycash',
            name='unique_daily_cash_per_branch_and_date',
        ),
        migrations.AddField(
            model_name='dailycash',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el cierre fue eliminado lógicamente.'),
        ),
        migrations.AddIndex(
            model_name='dailycash',
            index=models.Index(fields=['company', 'branch', 'date'], name='cash_dailyc_company_b3b568_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycash',
            index=models.Index(fields=['is_deleted'], name='cash_dailyc_is_dele_b7706e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycash',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'branch', 'date'), name='unique_daily_cash_active_per_branch_and_date'),
        ),
    ]
